config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :gadgets do
    collection do
      get :search
    end
  end

  root 'welcome#index'
end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  validates :name, presence: true,  length: { minimum: 3 }

  has_many :images, dependent: :destroy

  accepts_nested_attributes_for :images, reject_if: Proc.new { |a| a['image'].nil? }

  default_scope { includes(:images) }

  def self.get_by(owner_id)
    owner_id.nil? ? all : where("user_id = #{owner_id}")
  end

  def self.search(search, user_id)
    if search
      search_condition = "%#{search}%"
      where('(name LIKE ? OR description LIKE ?) AND (user_id=?)', search_condition, search_condition, user_id)
    else
      where('user_id=?', user_id)
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gadget

  has_attached_file :image,
    styles: { large: '600x600>', medium: '300x300>', thumb: '100x100>' },
    url: '/assets/images/:id/:style/:basename.:extension',
    path: ':rails_root/public/assets/images/:id/:style/:basename.:extension'

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/

  validates_attachment_size :image, in: 0..1.megabyte
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :set_gadget, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @gadgets = Gadget.get_by current_user.to_param
  end

  def show
  end

  def new
    @gadget = Gadget.new
  end

  def edit
  end

  def create
    @gadget = Gadget.new(gadget_params)

    respond_to do |format|
      if @gadget.save
        format.html { redirect_to @gadget, notice: 'Gadget was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to @gadget, notice: 'Gadget was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @gadget.destroy
    respond_to do |format|
      format.html { redirect_to gadgets_url, notice: 'Gadget was successfully destroyed.' }
    end
  end

  def search
    @gadgets = Gadget.search(params[:q], current_user.to_param)
  end

  private

  def set_gadget
    @gadget = Gadget.find(params[:id])
  end

  def gadget_params
    params.require(:gadget).permit(:name, :description, :user_id, images_attributes: [:image])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gadgets/_form.html.slim
= form_for @gadget, html: { multipart: true } do |f|
  - if @gadget.errors.any?
    #error_explanation
      h2 = "#{pluralize(@gadget.errors.count, "error")} prohibited this gadget from being saved:"
      ul
        - @gadget.errors.full_messages.each do |message|
          li = message
  = f.hidden_field :user_id, value: @gadget.new_record? ? current_user.id : @gadget.user_id

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = render partial: 'shared/image', collection: @gadget.images

    = f.fields_for :images, @gadget.images.build do | builder |
      .form-group
        = builder.label :image
        = builder.file_field :image

  .form-group
    = f.label :description
    = f.text_area :description, size: '30x10', class: 'form-control'

  .form-group
    = f.submit nil, class: 'btn btn-primary'

app/views/gadgets/_gadget.html.slim
.item.col-xs-4.col-lg-4
    - unless gadget.images.empty?
      .gadget
        = image_tag gadget.images.first.image.url(:thumb)
    .caption
      h4.group.inner.list-group-item-heading
        = link_to gadget.name, gadget
      p.group.inner.list-group-item-text
        = gadget.description.truncate(100, separator: '...')
      - if user_signed_in?
        .row
          .col-xs-12.col-md-3 = link_to 'Show', gadget, class: "show_gadget_#{gadget.to_param}"
          .col-xs-12.col-md-3 = link_to 'Edit', edit_gadget_path(gadget), class: "edit_gadget_#{gadget.to_param}"
          .col-xs-12.col-md-3 = link_to 'Destroy', gadget, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "delete_gadget_#{gadget.to_param}"

app/views/gadgets/edit.html.slim
.col-md-8.col-md-offset-2
  h1 Editing gadget

  == render 'form'

  = link_to 'Show', @gadget
  '|
  = link_to 'Back', gadgets_path

app/views/gadgets/index.html.slim
.col-md-8.col-md-offset-2
  .well.well-sm
    .btn-group
      a#list.btn.btn-default.btn-sm href="#"
        span.glyphicon.glyphicon-th-list
          | List
      a#grid.btn.btn-default.btn-sm href="#"
        span.glyphicon.glyphicon-th
          | Grid

  #gadgets.row.list-group
    = render partial: 'gadget', collection: @gadgets

  = link_to 'New Gadget', new_gadget_path

app/views/gadgets/new.html.slim
.col-md-8.col-md-offset-2
  h1 New gadget

  == render 'form'

  = link_to 'Back', gadgets_path

app/views/gadgets/search.html.slim
.col-md-8.col-md-offset-2
  .well.well-sm
    .btn-group
      a#list.btn.btn-default.btn-sm href="#"
        span.glyphicon.glyphicon-th-list
          | List
      a#grid.btn.btn-default.btn-sm href="#"
        span.glyphicon.glyphicon-th
          | Grid

  #gadgets.row.list-group
    = render partial: 'gadget', collection: @gadgets

app/views/gadgets/show.html.slim
.col-md-8.col-md-offset-2
  p#notice = notice
  .row
    - unless @gadget.images.empty?
      .col-md-4.column.image-gallery
        .preview
          = link_to @gadget.images.first.image.url(:large) do
              = image_tag @gadget.images.first.image.url(:medium)
        .thumbs
          = render partial: 'shared/image', collection: @gadget.images
    .col-md-8.column
      p
        = @gadget.name
      p
        = @gadget.description

  = link_to 'Edit', edit_gadget_path(@gadget)
  '|
  = link_to 'Back', gadgets_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GadgetTdd
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container-fluid
      .row-fluid
        .col-md-12
          nav.navbar.navbar-default role="navigation"
            .navbar-header
              button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
                span.sr-only Toggle navigation
                span.icon-bar
                span.icon-bar
                span.icon-bar
              = link_to 'GC', root_url, class: 'navbar-brand'

            = render 'shared/navigation'

          - if notice
            .alert.alert-success.alert-dismissable
              button.close aria-hidden="true" data-dismiss="alert" type="button"
                | ×
              h4
                | Notice!
              p
                = notice

          - if alert
            .alert.alert-danger.alert-dismissable
              button.close aria-hidden="true" data-dismiss="alert" type="button"
                | ×
              h4
                | Alert!
              p
                = alert
          .row-fluid
            = yield

app/views/shared/_image.html.slim
p
  = image_tag image.image.url(:thumb)

app/views/shared/_navigation.html.slim
#bs-example-navbar-collapse-1.collapse.navbar-collapse
  ul.nav.navbar-nav
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        | Gadgets
        strong.caret
      ul.dropdown-menu
        li
          = link_to 'Add new gadget', new_gadget_path, class: 'navbar-link'
        li
          = link_to 'List all gadgets', gadgets_path, class: 'navbar-link'
  ul.nav.navbar-nav.navbar-right
    - unless user_signed_in?
      li
        = link_to "Login", new_user_session_path, class: 'navbar-link'
      li
        = link_to "Sign up", new_user_registration_path, class: 'navbar-link'
    - else
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#"
          | Logged in as &nbsp;
          |
          strong = current_user.email
          strong.caret
        ul.dropdown-menu
          li
            = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
          li
            = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    br

app/views/welcome/index.html.slim
h1 Welcome#index
p Find me in app/views/welcome/index.html.slim